openapi: 3.0.2
info:
  description: WorldCat Metadata API
  version: 2.0.0
  title: WorldCat Metadata API
servers:
  - url: https://metadata.api.oclc.org
    description: PROD
security:
  - worldcat_metadata_auth:
      - WorldCatMetadataAPI
paths:
  /worldcat/manage/bibs/validate/{validationLevel}:
    post:
      tags:
        - Manage Bibliographic Records
      summary: Validate a Bibliographic Record
      description: Given a Bibliographic record, apply the validation rules that conform to MARC standards.
      operationId: validate-a-bib
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_bibs
  /worldcat/manage/bibs/current:
    get:
      tags:
        - Manage Bibliographic Records
      summary: Retrieve the current OCLC Numbers from WorldCat.
      description: Given one or more OCLC Numbers, check WorldCat for those numbers. It will return the most current OCLC Number(s) associated w/ the OCLC Number(s) provided. If an OCLC Number does not exist or is invalid, a result of null is returned for the requested number.
      operationId: get-current-oclc-number
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_bibs
            - WorldCatMetadataAPI:match_bibs
  /worldcat/manage/bibs:
    post:
      tags:
        - Manage Bibliographic Records
      summary: Create a Bibliographic Record
      description: Given a bibliographic record, create it in WorldCat... if it does not exist.
      operationId: bib-create
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_bibs
  /worldcat/manage/bibs/{oclcNumber}:
    get:
      tags:
        - Manage Bibliographic Records
      summary: Retrieve a Bibliographic record
      description: Given an OCLC Number, retrieve a Bibliographic record, if it exists in WorldCat.
      operationId: bib-read
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_bibs
            - WorldCatMetadataAPI:view_marc_bib
    put:
      tags:
        - Manage Bibliographic Records
      summary: Replace a Bibliographic record
      description: Given an OCLC Number, replace a Bibliographic record.  If the Bibliographic record does not exist, then a new Bibliographic record will be created.
      operationId: bib-replace
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_bibs
  /worldcat/manage/bibs/match:
    post:
      tags:
        - Manage Bibliographic Records
      summary: Match a Bibliographic Record
      description: Given a Bibliographic record in textual MARC or MARCXML format, apply OCLC matching rules to provide a single best-matched WorldCat result if possible. Bibliographic input record must contain a minimum of a MARC 008 and a MARC 245 field. In the JSON response, numberOfRecords indicates the potentially matched number of records and briefRecords contains the single best-match as determined by the OCLC matching service.
      operationId: match-bib
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_bibs
            - WorldCatMetadataAPI:match_bibs
  /worldcat/manage/institution/holdings/current:
    get:
      tags:
        - Manage Institution
      summary: Retrieve the current institution holdings for Bibliographic records from WorldCat.
      description: Given one or more OCLC Numbers (up to 10), check WorldCat for the institution holdings. It will return current institution holdings information associated w/ the OCLC Number(s) provided. If an OCLC Number does not exist or is invalid, a result of null is returned for the current control number.
      operationId: get-current-holdings
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_holdings
  /worldcat/manage/institution/holdings/set:
    post:
      tags:
        - Manage Institution
      summary: Set a holding on a Bibliographic record.
      description: 'Given a Bibliographic record, unset a holding on the record. Note: ONLY one record is allowed in the request body.'
      operationId: set-a-holding
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_holdings
  /worldcat/manage/institution/holdings/unset:
    post:
      tags:
        - Manage Institution
      summary: Unset a holding on a Bibliographic record.
      description: 'Given a Bibliographic record, unset a holding on the record. Note: ONLY one record is allowed in the request body.'
      operationId: unset-a-holding
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_holdings
  /worldcat/manage/institution/holdings/{oclcNumber}/set:
    post:
      tags:
        - Manage Institution
      summary: Set the holding on a Bibliographic record for an institution by OCLC Number.
      description: Given an Identifier (OCLC Number), set the holding on the appropriate Bibliographic record.
      operationId: set-holding-for-one-or-multiple-institutions
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_holdings
  /worldcat/manage/institution/holdings/{oclcNumber}/unset:
    post:
      tags:
        - Manage Institution
      summary: Unset the holding on a Bibliographic record for an institution by OCLC Number.
      description: Given an Identifier (OCLC Number), unset the holding on the appropriate Bibliographic record.
      operationId: Unset-holding-for-one-or-multiple-institutions
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_holdings
  /worldcat/manage/institution/holdings/move:
    post:
      tags:
        - Manage Institution
      summary: Move a holding from one Bibliographic record to another.
      description: Given source and target OCLC numbers, move the holdings from the source to the target.
      operationId: move-holdings
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_holdings
  /worldcat/manage/institution/holding-codes:
    get:
      tags:
        - Manage Institution
      summary: Retrieve Holding Codes
      description: Retrieve all the Holding Codes associated with the authenticated institution.
      operationId: retrieve-holding-codes
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_bibs
            - WorldCatMetadataAPI:get_holding_codes
  /worldcat/manage/lbds:
    post:
      tags:
        - Manage Local Bibliographic Data
      summary: Create a Local Bibliographic Data record.
      description: Given a Local Bibliographic Data record, create it in WorldCat.
      operationId: lbd-create
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_lbds
  /worldcat/manage/lbds/{controlNumber}:
    get:
      tags:
        - Manage Local Bibliographic Data
      summary: Retrieve a Local Bibliographic Data record.
      description: Given a Control Number, retrieve a Local Bibliographic Data record.
      operationId: lbd-read
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_lbds
    put:
      tags:
        - Manage Local Bibliographic Data
      summary: Replace a Local Bibliographic Data record.
      description: Given a Control Number, find the associated Local Bibliographic Data record and replace it. If the Control Number is not found in WorldCat, then the provided Local Bibliographic Data record will be created.
      operationId: lbd-update
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_lbds
    delete:
      tags:
        - Manage Local Bibliographic Data
      summary: Delete a Local Bibliographic Data record.
      description: Given a Control Number, delete the associated Local Bibliographic Data record.
      operationId: lbd-delete
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_lbds
  /worldcat/manage/lhrs:
    post:
      tags:
        - Manage Local Holdings Records
      summary: Create a Local Holdings Record
      description: Given a Local Holdings Record, create it in WorldCat.
      operationId: lhr-create
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_lhrs
  /worldcat/manage/lhrs/{controlNumber}:
    get:
      tags:
        - Manage Local Holdings Records
      summary: Retrieve a Local Holdings Record
      description: Given an Accesion Number, retrieve the associated Local Holdings Record.
      operationId: lhr-read
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_lhrs
    put:
      tags:
        - Manage Local Holdings Records
      summary: Replace a Local Holdings Record.
      description: Given a Control Number, find the associated Local Holdings Record and replace it. If the Control Number is not found in WorldCat, then the provided Local Holdings Record will be created.
      operationId: lhr-update
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_lhrs
    delete:
      tags:
        - Manage Local Holdings Records
      summary: Delete a Local Holdings Record
      description: Given a Control Number, delete a Local Holdings record.
      operationId: lhr-delete
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:manage_institution_lhrs
  /worldcat/search/bibs-retained-holdings:
    get:
      tags:
        - Search Member Shared Print Holdings
      summary: Find member shared print holdings for a known item
      description: Given a known item, find the member library holdings with a commitment to retain (Shared Print)
      operationId: find-bib-retained-holdings
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_retained_holdings
  /worldcat/search/bibs-summary-holdings:
    get:
      tags:
        - Search Member General Holdings
      summary: Get summary of holdings for a known item
      description: Given a known item, get summary of holdings
      operationId: find-bib-summary-holdings
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_summary_holdings
  /worldcat/search/brief-bibs:
    get:
      tags:
        - Search Bibliographic Resources
      summary: Search Brief Bibliographic Resources
      description: Search Brief Bibliographic Resources
      operationId: search-brief-bibs
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_brief_bib
  /worldcat/search/brief-bibs/{oclcNumber}:
    get:
      tags:
        - Search Bibliographic Resources
      summary: Retrieve specific Brief Bibliographic Resource
      description: Retrieve specific Bibliographic Resource
      operationId: retrieve-brief-bib
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_brief_bib
  /worldcat/search/brief-bibs/{oclcNumber}/other-editions:
    get:
      tags:
        - Search Bibliographic Resources
      summary: Retrieve Other Editions related to a particular Bibliographic Resource
      description: Retrieve Other Editions related to a particular Bibliographic Resource
      operationId: retrieve-other-editions
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_brief_bib
  /worldcat/search/classification-bibs/{oclcNumber}:
    get:
      tags:
        - Search Bibliographic Resources
      summary: Retrieve classification reccomendations for an oclcNumber
      description: Retrieve classification reccomendations for an oclcNumber
      operationId: get-classifications
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_brief_bib
  /worldcat/search/bibs/{oclcNumber}:
    get:
      tags:
        - Bibliographic Resources
      summary: Retrieve specific Bibliographic Resource
      description: Retrieve specific Bibliographic Resource
      operationId: retrieve-bib
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_bib
  /worldcat/search/summary-holdings:
    get:
      tags:
        - Search Member General Holdings
      summary: Get summary of holdings for a known item
      description: Given a known item, get summary of holdings
      operationId: find-holdings
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_summary_holdings
  /worldcat/search/retained-holdings:
    get:
      tags:
        - Search Local Holdings Resources
      summary: Search for shared print LHR Resources
      description: Search for shared print LHR Resources
      operationId: search-retrained-lhr
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_retained_holdings
  /worldcat/search/my-local-bib-data/{controlNumber}:
    get:
      tags:
        - Local Bib Resources
      summary: Retrieve LBD Resource
      description: Retrieve LBD Resource
      operationId: retrieve-lbd
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_my_local_bib_data
  /worldcat/search/my-local-bib-data:
    get:
      tags:
        - Local Bib Resources
      summary: Search LBD Resources
      description: |
        Search LBD Resources <a href="https://help.oclc.org/Librarian_Toolbox/Searching_WorldCat_Indexes/Local_bibliographic_data_records/Local_bibliographic_data_record_indexes_A-Z">Learn more about the indexes available</a>
      operationId: search-lbd
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_my_local_bib_data
  /worldcat/search/my-holdings/{controlNumber}:
    get:
      tags:
        - Search Local Holdings Resources
      summary: Retrieve LHR Resource
      description: Retrieve LHR Resource
      operationId: retrieve-lhr
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_my_holdings
            - WorldCatMetadataAPI:view_my_holdings_private_notes
  /worldcat/search/my-holdings:
    get:
      tags:
        - Search Local Holdings Resources
      summary: Search LHR Resources
      description: Search LHR Resources
      operationId: search-lhr
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_my_holdings
            - WorldCatMetadataAPI:view_my_holdings_private_notes
  /worldcat/browse/my-holdings:
    get:
      tags:
        - Search Local Holdings Resources
      summary: Browse LHR Resources
      description: Browse LHR Resources
      operationId: browse-lhr
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:view_my_holdings
            - WorldCatMetadataAPI:view_my_holdings_private_notes
  /worldcat/manage/institution-config/branch-shelving-locations:
    get:
      tags:
        - Manage Institution
      operationId: manage-institution-branch-config
      summary: Retrieve branch holding codes and shelving locations
      description: Retrieve branch holding codes or shelving locations within a branch associated with an authenticated institution.
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:get_holding_codes
            - WorldCatMetadataAPI:manage_bibs
  /worldcat/search/institution:
    get:
      tags:
        - Manage Institution
      operationId: find-institution-by-identifier
      summary: Fetch Identifiers for an Institution
      description: Fetch Identifiers for an Institution
      security:
        - worldcat_metadata_auth:
            - WorldCatMetadataAPI:get_holding_codes
            - WorldCatMetadataAPI:manage_bibs
components:
  securitySchemes:
    worldcat_metadata_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.oclc.org/token
          scopes:
            WorldCatMetadataAPI:view_brief_bib: view brief bibliographic data
            WorldCatMetadataAPI:view_bib: view full bibliographic data
            WorldCatMetadataAPI:view_marc_bib: view marc bibliographic data
            WorldCatMetadataAPI:match_bibs: match bibliographic records
            WorldCatMetadataAPI:get_holding_codes: retrieve holding codes
            WorldCatMetadataAPI:manage_bibs: manage bibliographic data
            WorldCatMetadataAPI:view_retained_holdings: view holdings which libraries have chosen to retain
            WorldCatMetadataAPI:view_summary_holdings: view summary information about library holdings
            WorldCatMetadataAPI:view_my_holdings: view detailed information about the authentication institution's holdings
            WorldCatMetadataAPI:view_my_holdings_private_notes: view private notes in holdings data
            WorldCatMetadataAPI:manage_institution_holdings: manage institution holdings
            WorldCatMetadataAPI:view_my_local_bib_data: view local bibliographic data from the authenticate institution
            WorldCatMetadataAPI:manage_institution_lbds: manage institution local bibliographic data records
            WorldCatMetadataAPI:manage_institution_lhrs: manage institution local holdings data records
            enhMetadataAPI:fieldTransfer: field transfer functionality
        authorizationCode:
          authorizationUrl: https://oauth.oclc.org/auth
          tokenUrl: https://oauth.oclc.org/token
          scopes:
            WorldCatMetadataAPI:view_brief_bib: view brief bibliographic data
            WorldCatMetadataAPI:view_bib: view full bibliographic data
            WorldCatMetadataAPI:view_marc_bib: view marc bibliographic data
            WorldCatMetadataAPI:match_bibs: match bibliographic records
            WorldCatMetadataAPI:get_holding_codes: retrieve holding codes
            WorldCatMetadataAPI:manage_bibs: manage bibliographic data
            WorldCatMetadataAPI:view_retained_holdings: view holdings which libraries have chosen to retain
            WorldCatMetadataAPI:view_summary_holdings: view summary information about library holdings
            WorldCatMetadataAPI:view_my_holdings: view detailed information about the authentication institution's holdings
            WorldCatMetadataAPI:view_my_holdings_private_notes: view private notes in holdings data
            WorldCatMetadataAPI:manage_institution_holdings: manage institution holdings
            WorldCatMetadataAPI:view_my_local_bib_data: view local bibliographic data from the authenticate institution
            WorldCatMetadataAPI:manage_institution_lbds: manage institution local bibliographic data records
            WorldCatMetadataAPI:manage_institution_lhrs: manage institution local holdings data records
            enhMetadataAPI:fieldTransfer: field transfer functionality